font:
  normal:
    family: mononoki Nerd Font Mono
  bold:
    family: mononoki Nerd Font Mono
    style: Bold
  italic:
    family: mononoki Nerd Font Mono
    style: Italic
  size: 14

env:
  term: xterm-256color

window:
  padding:
    x: 8
    y: 8
  decorations: none
  # opacity: 0.9

# Base16 Gruvbox dark, pale 256 - alacritty color config
# Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)
colors:
  # Default colors
  primary:
    background: '0x262626'
    foreground: '0xdab997'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x262626'
    cursor: '0xdab997'

  # Normal colors
  normal:
    black:   '0x262626'
    red:     '0xd75f5f'
    green:   '0xafaf00'
    yellow:  '0xffaf00'
    blue:    '0x83adad'
    magenta: '0xd485ad'
    cyan:    '0x85ad85'
    white:   '0xdab997'

  # Bright colors
  bright:
    black:   '0x8a8a8a'
    red:     '0xd75f5f'
    green:   '0xafaf00'
    yellow:  '0xffaf00'
    blue:    '0x83adad'
    magenta: '0xd485ad'
    cyan:    '0x85ad85'
    white:   '0xebdbb2'

  indexed_colors:
    - { index: 16, color: '0xff8700' }
    - { index: 17, color: '0xd65d0e' }
    - { index: 18, color: '0x3a3a3a' }
    - { index: 19, color: '0x4e4e4e' }
    - { index: 20, color: '0x949494' }
    - { index: 21, color: '0xd5c4a1' }

# # Base16 Atelier Cave 256 - alacritty color config
# # Bram de Haan (http://atelierbramdehaan.nl)
# colors:
#   # Default colors
#   primary:
#     background: '0x19171c'
#     foreground: '0x8b8792'

#   # Colors the cursor will use if `custom_cursor_colors` is true
#   cursor:
#     text: '0x19171c'
#     cursor: '0x8b8792'

#   # Normal colors
#   normal:
#     black:   '0x19171c'
#     red:     '0xbe4678'
#     green:   '0x2a9292'
#     yellow:  '0xa06e3b'
#     blue:    '0x576ddb'
#     magenta: '0x955ae7'
#     cyan:    '0x398bc6'
#     white:   '0x8b8792'

#   # Bright colors
#   bright:
#     black:   '0x655f6d'
#     red:     '0xbe4678'
#     green:   '0x2a9292'
#     yellow:  '0xa06e3b'
#     blue:    '0x576ddb'
#     magenta: '0x955ae7'
#     cyan:    '0x398bc6'
#     white:   '0xefecf4'

#   indexed_colors:
#     - { index: 16, color: '0xaa573c' }
#     - { index: 17, color: '0xbf40bf' }
#     - { index: 18, color: '0x26232a' }
#     - { index: 19, color: '0x585260' }
#     - { index: 20, color: '0x7e7887' }
#     - { index: 21, color: '0xe2dfe7' }

# # Base16 Gruvbox dark, medium 256 - alacritty color config
# # Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)
# colors:
#   # Default colors
#   primary:
#     background: '0x282828'
#     foreground: '0xd5c4a1'

#   # Colors the cursor will use if `custom_cursor_colors` is true
#   cursor:
#     text: '0x282828'
#     cursor: '0xd5c4a1'

#   # Normal colors
#   normal:
#     black:   '0x282828'
#     red:     '0xfb4934'
#     green:   '0xb8bb26'
#     yellow:  '0xfabd2f'
#     blue:    '0x83a598'
#     magenta: '0xd3869b'
#     cyan:    '0x8ec07c'
#     white:   '0xd5c4a1'

#   # Bright colors
#   bright:
#     black:   '0x665c54'
#     red:     '0xfb4934'
#     green:   '0xb8bb26'
#     yellow:  '0xfabd2f'
#     blue:    '0x83a598'
#     magenta: '0xd3869b'
#     cyan:    '0x8ec07c'
#     white:   '0xfbf1c7'

#   indexed_colors:
#     - { index: 16, color: '0xfe8019' }
#     - { index: 17, color: '0xd65d0e' }
#     - { index: 18, color: '0x3c3836' }
#     - { index: 19, color: '0x504945' }
#     - { index: 20, color: '0xbdae93' }
#     - { index: 21, color: '0xebdbb2' }

# Base16 Snazzy 256 - alacritty color config
# Chawye Hsu (https://github.com/h404bi) based on Hyper Snazzy Theme (https://github.com/sindresorhus/hyper-snazzy)
# colors:
#   # Default colors
#   primary:
#     background: '0x282a36'
#     foreground: '0xe2e4e5'

#   # Colors the cursor will use if `custom_cursor_colors` is true
#   cursor:
#     text: '0x282a36'
#     cursor: '0xe2e4e5'

#   # Normal colors
#   normal:
#     black:   '0x282a36'
#     red:     '0xff5c57'
#     green:   '0x5af78e'
#     yellow:  '0xf3f99d'
#     blue:    '0x57c7ff'
#     magenta: '0xff6ac1'
#     cyan:    '0x9aedfe'
#     white:   '0xe2e4e5'

#   # Bright colors
#   bright:
#     black:   '0x78787e'
#     red:     '0xff5c57'
#     green:   '0x5af78e'
#     yellow:  '0xf3f99d'
#     blue:    '0x57c7ff'
#     magenta: '0xff6ac1'
#     cyan:    '0x9aedfe'
#     white:   '0xf1f1f0'

#   indexed_colors:
#     - { index: 16, color: '0xff9f43' }
#     - { index: 17, color: '0xb2643c' }
#     - { index: 18, color: '0x34353e' }
#     - { index: 19, color: '0x43454f' }
#     - { index: 20, color: '0xa5a5a9' }
#     - { index: 21, color: '0xeff0eb' }
  
# Base16 Tomorrow Night 256 - alacritty color config
# Chris Kempson (http://chriskempson.com)
# colors:
#   # Default colors
#   primary:
#     background: '0x2d2d2d'
#     foreground: '0xcccccc'

#   # Colors the cursor will use if `custom_cursor_colors` is true
#   cursor:
#     text: '0x2d2d2d'
#     cursor: '0xcccccc'

#   # Normal colors
#   normal:
#     black:   '0x2d2d2d'
#     red:     '0xf2777a'
#     green:   '0x99cc99'
#     yellow:  '0xffcc66'
#     blue:    '0x6699cc'
#     magenta: '0xcc99cc'
#     cyan:    '0x66cccc'
#     white:   '0xcccccc'

#   # Bright colors
#   bright:
#     black:   '0x999999'
#     red:     '0xf2777a'
#     green:   '0x99cc99'
#     yellow:  '0xffcc66'
#     blue:    '0x6699cc'
#     magenta: '0xcc99cc'
#     cyan:    '0x66cccc'
#     white:   '0xffffff'

#   indexed_colors:
#     - { index: 16, color: '0xf99157' }
#     - { index: 17, color: '0xa3685a' }
#     - { index: 18, color: '0x393939' }
#     - { index: 19, color: '0x515151' }
#     - { index: 20, color: '0xb4b7b4' }
#     - { index: 21, color: '0xe0e0e0' }



# TokyoNight Alacritty Colors
# colors:
#   # Default colors
#   primary:
#     background: '0x24283b'
#     foreground: '0xc0caf5'

#   # Normal colors
#   normal:
#     black:   '0x1D202F'
#     red:     '0xf7768e'
#     green:   '0x9ece6a'
#     yellow:  '0xe0af68'
#     blue:    '0x7aa2f7'
#     magenta: '0xbb9af7'
#     cyan:    '0x7dcfff'
#     white:   '0xa9b1d6'

#   # Bright colors
#   bright:
#     black:   '0x414868'
#     red:     '0xf7768e'
#     green:   '0x9ece6a'
#     yellow:  '0xe0af68'
#     blue:    '0x7aa2f7'
#     magenta: '0xbb9af7'
#     cyan:    '0x7dcfff'
#     white:   '0xc0caf5'

#   indexed_colors:
#     - { index: 16, color: '0xff9e64' }
#     - { index: 17, color: '0xdb4b4b' }

# colors:
#   # Default colors
#   primary:
#     background: '0x1a1b26'
#     foreground: '0xa9b1d6'

#   # Normal colors
#   normal:
#     black:   '0x32344a'
#     red:     '0xf7768e'
#     green:   '0x9ece6a'
#     yellow:  '0xe0af68'
#     blue:    '0x7aa2f7'
#     magenta: '0xad8ee6'
#     cyan:    '0x449dab'
#     white:   '0x787c99'

#   # Bright colors
#   bright:
#     black:   '0x444b6a'
#     red:     '0xff7a93'
#     green:   '0xb9f27c'
#     yellow:  '0xff9e64'
#     blue:    '0x7da6ff'
#     magenta: '0xbb9af7'
#     cyan:    '0x0db9d7'
#     white:   '0xacb0d0'

# colors:
#   # theme: horizon
#    primary:
#      background: "0x232530"
#      foreground: "0xC7C9CB"
#    normal:
#      black:   "0x16161C"
#      white:   "0xFDF0ED"
#      red:     "0xE95678"
#      green:   "0x09F7A0"
#      yellow:  "0xFAB795"
#      blue:    "0x25B2BC"
#      magenta: "0x6C6F93"
#      cyan:    "0x27D797"
#    bright:
#      black:   "0x1A1C23"
#      white:   "0xFDF0ED"
#      red:     "0xF09383"
#      green:   "0x21BFC2"
#      blue:    "0x21BFC2"
#      magenta: "0xB877DB"
#      cyan:    "0x59E3E3"
#      yellow:  "0xFAB795"

  # theme: laserwave
  # primary:
  #   background: "0x27212E"
  #   foreground: "0xFFFFFF"
  # normal:
  #   black:   "0x222228"
  #   white:   "0xEEEEFF"
  #   red:     "0x964477"
  #   green:   "0x77DDCC"
  #   yellow:  "0xFFEE66"
  #   blue:    "0x336677"
  #   magenta: "0xBB88CC"
  #   cyan:    "0x667788"
  # bright:
  #   black:   "0x222222"
  #   white:   "0xEEEEEE"
  #   red:     "0xFFBB55"
  #   green:   "0x448877"
  #   blue:    "0x44BBCC"
  #   magenta: "0xEE66BB"
  #   cyan:    "0xBBDDEE"
  #   yellow:  "0xFFEE66"
