font:
  normal:
    family: mononoki Nerd Font Mono
  bold:
    family: mononoki Nerd Font Mono
    style: Bold
  italic:
    family: mononoki Nerd Font Mono
    style: Italic
  size: 16

env:
  term: xterm-256color

window:
  decorations: none
  opacity: 1.0

# Nightfox Alacritty Colors
# Style: carbonfox
# Upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/carbonfox/alacritty.yml
# colors:
#   # Default colors
#   primary:
#     background: '0x161616'
#     foreground: '0xf2f4f8'
#   # Normal colors
#   normal:
#     black:   '0x282828'
#     red:     '0xee5396'
#     green:   '0x25be6a'
#     yellow:  '0x08bdba'
#     blue:    '0x78a9ff'
#     magenta: '0xbe95ff'
#     cyan:    '0x33b1ff'
#     white:   '0xdfdfe0'
#   # Bright colors
#   bright:
#     black:   '0x484848'
#     red:     '0xf16da6'
#     green:   '0x46c880'
#     yellow:  '0x2dc7c4'
#     blue:    '0x8cb6ff'
#     magenta: '0xc8a5ff'
#     cyan:    '0x52bdff'
#     white:   '0xe4e4e5'
#   indexed_colors:
#     - { index: 16, color: '0x3ddbd9' }
#     - { index: 17, color: '0xff7eb6' }

colors:
  # Default colors
  primary:
    background: "0x232136"
    foreground: "0xe0def4"
  # Normal colors
  normal:
    black: "0x393552"
    red: "0xeb6f92"
    green: "0xa3be8c"
    yellow: "0xf6c177"
    blue: "0x569fba"
    magenta: "0xc4a7e7"
    cyan: "0x9ccfd8"
    white: "0xe0def4"
  # Bright colors
  bright:
    black: "0x47407d"
    red: "0xf083a2"
    green: "0xb1d196"
    yellow: "0xf9cb8c"
    blue: "0x65b1cd"
    magenta: "0xccb1ed"
    cyan: "0xa6dae3"
    white: "0xe2e0f7"
  indexed_colors:
    - { index: 16, color: "0xea9a97" }
    - { index: 17, color: "0xeb98c3" }
