font:
  normal:
    family: mononoki Nerd Font Mono
  bold:
    family: mononoki Nerd Font Mono
    style: Bold
  italic:
    family: mononoki Nerd Font Mono
    style: Italic
  size: 13

window:
  decorations: none
  opacity: 0.9

colors:
  # theme: horizon
   primary:
     background: "0x232530"
     foreground: "0xC7C9CB"
   normal:
     black:   "0x16161C"
     white:   "0xFDF0ED"
     red:     "0xE95678"
     green:   "0x09F7A0"
     yellow:  "0xFAB795"
     blue:    "0x25B2BC"
     magenta: "0x6C6F93"
     cyan:    "0x27D797"
   bright:
     black:   "0x1A1C23"
     white:   "0xFDF0ED"
     red:     "0xF09383"
     green:   "0x21BFC2"
     blue:    "0x21BFC2"
     magenta: "0xB877DB"
     cyan:    "0x59E3E3"
     yellow:  "0xFAB795"

  # theme: laserwave
  # primary:
  #   background: "0x27212E"
  #   foreground: "0xFFFFFF"
  # normal:
  #   black:   "0x222228"
  #   white:   "0xEEEEFF"
  #   red:     "0x964477"
  #   green:   "0x77DDCC"
  #   yellow:  "0xFFEE66"
  #   blue:    "0x336677"
  #   magenta: "0xBB88CC"
  #   cyan:    "0x667788"
  # bright:
  #   black:   "0x222222"
  #   white:   "0xEEEEEE"
  #   red:     "0xFFBB55"
  #   green:   "0x448877"
  #   blue:    "0x44BBCC"
  #   magenta: "0xEE66BB"
  #   cyan:    "0xBBDDEE"
  #   yellow:  "0xFFEE66"
