import = [
  "~/.config/alacritty/colors/rose-pine/rose_pine.toml"
]

[font]
normal = { family = "mononoki Nerd Font Mono" }
bold = { family = "mononoki Nerd Font Mono", style = "bold" }
italic = { family = "mononoki Nerd Font Mono", style = "italic" }
size = 14

[env]
term = "xterm-256color"

[window]
decorations = "buttonless"
opacity = 1.0
padding = { x = 8, y = 8 }
