decoration {
  rounding = 10

  active_opacity = 1.0
  inactive_opacity = 0.9
  fullscreen_opacity = 1.0

  dim_inactive = true
  dim_strength = 0.1
  dim_special = 0.8

  blur {
  	enabled = true
  	size = 6
  	passes = 2
  	ignore_opacity = true
  	new_optimizations = true
  	special = true
  }
}

animations {
  enabled = yes

  bezier = wind, 0.05, 0.9, 0.1, 1.05
  bezier = winIn, 0.1, 1.1, 0.1, 1.1
  bezier = winOut, 0.3, -0.3, 0, 1
  bezier = liner, 1, 1, 1, 1

  animation = windows, 1, 2, wind, slide
  animation = windowsIn, 1, 2, winIn, slide
  animation = windowsOut, 1, 2, winOut, slide
  animation = windowsMove, 1, 2, wind, slide
  animation = border, 1, 1, liner
  animation = fade, 1, 2, default
  animation = workspaces, 1, 2, wind
}
