source = $HOME/.config/nord/hypr-nord.conf

dwindle {
  pseudotile = yes
  preserve_split = yes
  special_scale_factor = 0.8
}

master {
  new_status = master
  new_on_top = 1
  mfact = 0.5
}

general {
  border_size = 2
  gaps_in = 8
  gaps_out = 16

  resize_on_border = true

  col.active_border = $nord10
  col.inactive_border = $nord0

  layout = dwindle
}

input {
  kb_layout = us
  kb_variant =
  kb_model =
  kb_options =
  kb_rules =
  repeat_rate = 50
  repeat_delay = 300
  numlock_by_default = true
  left_handed = false
  follow_mouse = false
  float_switch_override_focus = false
  sensitivity = 0.05
  accel_profile = flat
}

group {
  col.border_active = $nord10

	groupbar {
		col.active = $nord0
  }
}

misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
	vfr = true
  mouse_move_enables_dpms = true
  enable_swallow = true
  swallow_regex = ^(kitty)$
  focus_on_activate = true
  initial_workspace_tracking = 0
  middle_click_paste = false
}

binds {
  workspace_back_and_forth = true
  allow_workspace_cycles = true
  pass_mouse_when_bound = false
}

xwayland {
  force_zero_scaling = true
}

cursor {
  no_hardware_cursors = false
  enable_hyprcursor = true
  warp_on_change_workspace = true
}

render {
  explicit_sync = 0 # disabled for nvidia
  explicit_sync_kms = 2
  direct_scanout = false
}
