require "settings"
require "plugins"
require "maps"
require "lualine-conf"
require "telescope-conf"
require "ale-conf"
require "closetag-conf"
require "cmp-conf"
require "prettier-conf"
require "lsp-conf"
require "treesitter-conf"
require "dap-conf"
require "dap-virtual-text-conf"
require "dashboard-conf"

vim.cmd [[filetype plugin on]]
