#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d term web gfx chat V

bspc config border_width            2
bspc config window_gap              12
bspc config focused_border_color    '#ed60ba'
bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc rule -a Gimp desktop='^3' state=floating follow=on
bspc rule -a Godot desktop='^3' state=floating
bspc rule -a Emacs desktop='^1' state=tiled

$HOME/.config/polybar/launch.sh
