source = $HOME/.config/nord/hypr-nord.conf

general {
    grace = 0
    ignore_empty_input = true
    immediate_render = true
}

background {
    monitor =
    path = $HOME/Pictures/wallpapers/nord_roads.png
    color = $nord0
    blur_passes = 2
}

input-field {
    monitor =
    size = 280, 48
    outline_thickness = 2
    dots_center = true
    outer_color = $nord3
    inner_color = $nord0
    font_color = $nord4
    font_family = mononoki Nerd Font Mono
    fade_on_empty = false
    placeholder_text = <span style="italic">Password...</span>
    rounding = 4
    check_color = $nord2
    fail_color = $nord11
    position = 0, -200
    halign = center
    valign = center
}
