$confs = $HOME/.config/hypr/configs

source = $confs/startup.conf
source = $confs/env.conf
source = $confs/monitors.conf
source = $confs/windows.conf
source = $confs/decor_anims.conf
source = $confs/keybinds.conf
source = $confs/settings.conf
