monitor = DP-1,3440x1440@175,0x0, 1

$terminal = kitty
$fileManager = dolphin
$menu = wofi --show drun
$browser = librewolf

exec-once = $browser
exec-once = $terminal

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 0

    sensitivity = -1.0
}

gestures {
    workspace_swipe = false
}

windowrulev2 = suppressevent maximize, class:.*
