$mainMod = SUPER

# system binds
bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exit,
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, F, exec, $browser

# move focus
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

# swap window
bind = $mainMod ALT, H, swapwindow, l
bind = $mainMod ALT, J, swapwindow, r
bind = $mainMod ALT, K, swapwindow, u
bind = $mainMod ALT, L, swapwindow, d

# switch workspaces
bind = $mainMod, Y, workspace, 1
bind = $mainMod, U, workspace, 2
bind = $mainMod, I, workspace, 3
bind = $mainMod, O, workspace, 4
bind = $mainMod, P, workspace, 5

# move active window to a workspace
bind = $mainMod SHIFT, H, movetoworkspace, 1
bind = $mainMod SHIFT, J, movetoworkspace, 2
bind = $mainMod SHIFT, K, movetoworkspace, 3
bind = $mainMod SHIFT, L, movetoworkspace, 4
bind = $mainMod SHIFT, :, movetoworkspace, 5

# Example special workspace (scratchpad)
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# scroll through existing workspaces
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
