font_family             Mononoki Nerd Font
bold_font               auto
italic_font             auto
font_size               22.0

tab_bar_edge            bottom
hide_window_decorations no
placement_strategy      left

map ctrl+shift+c        copy_to_clipboard
map ctrl+shift+v        paste_from_clipboard

# BEGIN_KITTY_THEME
# Nordfox
include current-theme.conf
# END_KITTY_THEME
